services:
  minio:
    image: minio/minio:RELEASE.2023-11-01T18-37-25Z
    command: minio server /data --address ":9000" --console-address ":9001"
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    extra_hosts:
      - mysticstorage.local:192.168.11.9
    volumes:
      - /volume1/docker/minio/config:/root/.minio
      - /volume1/docker/minio/data:/data
    environment:
      TZ: Asia/Tokyo
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: MinIO12345
    deploy:
      resources:
        limits:
          cpus: mid
          memory: 1g
