# kind create cluster --config kind-cluster.yaml
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-cluster
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.configs."mysticstorage.local:8443".tls]
      insecure_skip_verify = true
nodes:
  - role: control-plane
    image: kindest/node:v1.27.3
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraMounts:
      - containerPath: /var/lib/kubelet/config.json
        hostPath: config/registry/config.json
        readOnly: true
    extraPortMappings:
      # Ingress
      - containerPort: 80
        hostPort: 80
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        listenAddress: "0.0.0.0"
        protocol: TCP
      # ArgoCD
      - containerPort: 30080
        hostPort: 30080
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 30443
        hostPort: 30443
        listenAddress: "0.0.0.0"
        protocol: TCP
